# 第4章 NumPy基础：数组和矢量计算

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Numpy数组运算

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [5]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [6]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [8]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

### 大小相同的数组之间的比较会生成布尔值的数组

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [11]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

### 不同大小的数组之间的运算叫做广播（broadcasting）

## 基本的索引和切片

In [12]:
arr3 = np.arange(10)

In [13]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr3[5]

5

In [15]:
arr3[5:8]

array([5, 6, 7])

In [16]:
arr3[5:8] = 12

In [17]:
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### 数组切片是原始数组的视图，这意味着数据不会被复制，视图上的任何修改都会直接反映到源数据上

In [18]:
arr3_slice = arr3[5:8]

In [19]:
arr3_slice

array([12, 12, 12])

In [20]:
arr3_slice[1] = 12345

In [21]:
arr3

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [22]:
arr3_slice[:] = 64

In [23]:
arr3

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 如果想要得到的是ndarray切片的一份副本而非视图，就需要明确的进行复制操作

### arr3[5:8].copy()

In [24]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [25]:
arr2d[2]

array([7, 8, 9])

### 下面两种方式是等价的

In [26]:
arr2d[0][2]

3

In [27]:
arr2d[0, 2]

3

### 2*2*3数组

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### arr3d[0]是一个2*3数组

In [30]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
old_values = arr3d[0].copy()

In [32]:
arr3d[0] = 42

In [33]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[1, 0]

array([7, 8, 9])

In [35]:
x = arr3d[1]

In [36]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
x[0]

array([7, 8, 9])

## 切片索引

In [38]:
arr3

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
arr3[1:6]

array([ 1,  2,  3,  4, 64])

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [43]:
arr2d[1, :2]

array([4, 5])

In [44]:
arr2d[:2, 2]

array([3, 6])

In [45]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### 对切片的赋值操作也会扩散到整个区域

In [46]:
arr2d[:2, 1:] = 0

In [47]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [49]:
data = np.random.randn(7, 4)

In [50]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [51]:
data

array([[-0.24384974,  1.40511498, -0.09209562,  1.23686235],
       [ 1.00671886, -0.15362795,  0.62381656,  0.40435719],
       [-1.1687377 ,  0.33440335, -0.5257795 , -0.63162684],
       [ 0.22351181, -1.39684548, -1.58329009, -0.00617676],
       [ 0.39634257,  0.13881427, -0.42399195, -1.54865048],
       [ 0.48341729,  0.12111269,  0.89228649,  1.4047878 ],
       [ 1.470831  , -0.33193146,  0.97018514, -0.30904235]])

In [52]:
names =='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [53]:
data[names == 'Bob']

array([[-0.24384974,  1.40511498, -0.09209562,  1.23686235],
       [ 0.22351181, -1.39684548, -1.58329009, -0.00617676]])

In [54]:
data[names == 'Bob', 2:]

array([[-0.09209562,  1.23686235],
       [-1.58329009, -0.00617676]])

In [55]:
data[names == 'Bob', 3]

array([ 1.23686235, -0.00617676])

In [56]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [57]:
data[names != 'Bob']

array([[ 1.00671886, -0.15362795,  0.62381656,  0.40435719],
       [-1.1687377 ,  0.33440335, -0.5257795 , -0.63162684],
       [ 0.39634257,  0.13881427, -0.42399195, -1.54865048],
       [ 0.48341729,  0.12111269,  0.89228649,  1.4047878 ],
       [ 1.470831  , -0.33193146,  0.97018514, -0.30904235]])

In [58]:
data[~(names != 'Bob')]

array([[-0.24384974,  1.40511498, -0.09209562,  1.23686235],
       [ 0.22351181, -1.39684548, -1.58329009, -0.00617676]])

In [59]:
cond = names == 'Bob'

In [60]:
data[~cond]

array([[ 1.00671886, -0.15362795,  0.62381656,  0.40435719],
       [-1.1687377 ,  0.33440335, -0.5257795 , -0.63162684],
       [ 0.39634257,  0.13881427, -0.42399195, -1.54865048],
       [ 0.48341729,  0.12111269,  0.89228649,  1.4047878 ],
       [ 1.470831  , -0.33193146,  0.97018514, -0.30904235]])

In [61]:
mask = (names == 'Bob') | (names == 'Will')

In [62]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [63]:
data[mask]

array([[-0.24384974,  1.40511498, -0.09209562,  1.23686235],
       [-1.1687377 ,  0.33440335, -0.5257795 , -0.63162684],
       [ 0.22351181, -1.39684548, -1.58329009, -0.00617676],
       [ 0.39634257,  0.13881427, -0.42399195, -1.54865048]])

In [64]:
data[data < 0] = 0

In [65]:
data

array([[ 0.        ,  1.40511498,  0.        ,  1.23686235],
       [ 1.00671886,  0.        ,  0.62381656,  0.40435719],
       [ 0.        ,  0.33440335,  0.        ,  0.        ],
       [ 0.22351181,  0.        ,  0.        ,  0.        ],
       [ 0.39634257,  0.13881427,  0.        ,  0.        ],
       [ 0.48341729,  0.12111269,  0.89228649,  1.4047878 ],
       [ 1.470831  ,  0.        ,  0.97018514,  0.        ]])

In [66]:
data[names != 'Joe'] = 7

In [67]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.00671886,  0.        ,  0.62381656,  0.40435719],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.48341729,  0.12111269,  0.89228649,  1.4047878 ],
       [ 1.470831  ,  0.        ,  0.97018514,  0.        ]])

### 花式索引 Fancy indexing

In [71]:
arrf = np.empty((8, 4))

In [72]:
arrf

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [73]:
for i in range(8):
    arrf[i] = i
    

In [74]:
arrf

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [75]:
arrf[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [76]:
arrf[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [78]:
arrr = np.arange(32).reshape((8, 4))

In [79]:
arrr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
arrr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [83]:
arrr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 记住索引跟切片不一样，它总是将数据复制到新数组中

## 数组转置与轴对换

In [84]:
arrt = np.arange(15).reshape(3, 5)

In [85]:
arrt

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arrt.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [89]:
np.dot(arrt.T, arrt)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

### 对于高维数组，transpose

In [90]:
arrts = np.arange(16).reshape((2, 2, 4))

In [91]:
arrts

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arrts.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [93]:
arrts

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [94]:
arrts.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 通用函数，快速的元素级数组函数